version: "3.7"

services:
  skinshub-api:
    image: skinshub-api:latest
    container_name: skinshub-api
    build: .
    ports:
      - 8000:8000
    environment:
      - DatabaseHost=192.168.2.24
      - DatabasePort=3306
      - DatabaseUsername=root
      - DatabasePassword=admin
    volumes:
      - ./config:/opt/app/config
